version: '3.8'


services:

  postgres:

    image: postgres

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      PGDATA: /data/postgres

    volumes:

       - pg_data:/data/postgres

    ports:

      - "5432:5432"



  adminer:

    image: adminer:4.8.1

    ports:

      - "8081:8080"

    depends_on:

      - postgres



volumes:

  pg_data: